### PR TITLE
Add FileField to the field_to_type_mapping and change way that the in…

### PR DESCRIPTION
**Pull request by djaszak**
…coming FKs are prepared.

We had a problem when we wanted to use Sargilo with a model that had a subclass of FileField as a Field, therefore we added it to the according mapping. 
Second problem came up because we are working with PolymorphicModels in one of our Projects. We changed the way how we prepare incoming FKs so that getattr(model, attr) is not called in a way that causes an AttributeError. 

Please check that and give me some Feedback.

### CODE REVIEW

**Comment by nick-lehmann** [comment]
After my first glance at this, the changes look perfectly fine 👍🏻 Have you tested it with a model that is not a polymorphic with the same result as before the change?

**Comment by djaszak** [comment]
Our test fixture has also models that are not polymorphic, like e.g. the normal django user and it works perfectly fine.

**Comment by nick-lehmann** [comment]
Thanks 👍🏻 Will build and publish a newer version over the weekend.

**Comment by nick-lehmann** [comment]
Fixed in version `0.1.6` 👍🏻

**Comment by djaszak** [comment]
Thank you  👍🏻

**Pull request merged**
